version: "3"
services:
  postgres:
    container_name: sails-todo-postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: sails-todo-db

